### ISSUE TITLE
pybind11 needed at runtime?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pymodsecurity-feedstock#2]
Appears that [`pybind11` is installed at runtime]( https://github.com/conda-forge/pymodsecurity-feedstock/blob/80f37ba67bbd13690ebf858fb37b0393459633ed/recipe/meta.yaml#L35 ). However am unclear on why that dependency is needed outside of the build. Could someone please clarify?

**Comment by GustavoKatel** [comment]
@jakirkham . `pybind11` is not required at runtime. Thanks for noting that. I will update the recipe
